[package]
name = "rbx-rsml"
version = "0.1.2"
edition = "2021"
description = "A lexer and parser for the RSML language."
homepage = "https://www.rsml.style"
repository = "https://github.com/rbx-rsml/rsml-rust.git"
readme = "README.md"
license = "MIT"

[dependencies]
phf = "0.11.3"
phf_macros = "0.11.3"
rbx_types = { version = "2.0.0", features = ["serde"] }
rbx_types_ops = "0.0.8"
logos = "0.15.0"
regex = "1.11.1"
num-traits = "0.2.19"
guarded = "0.0.2"
palette = "0.7.6"
serde_json = "1.0.140"
indexmap = "2.9.0"

[build-dependencies]
serde_json = "1.0.140"
phf = "0.11.3"
phf_codegen = "0.11.3"

[lib]
name = "rbx_rsml"
path = "src/lib.rs"
test = true
doctest = true
bench = true
doc = true 
harness = true
edition = "2021"
crate-type = ["lib"]