[package]
name = "rbx-rsml"
version = "0.0.1"
edition = "2021"
description = "A lexer and parser for the RSML language."
homepage = "https://www.rsml.style"
repository = "https://github.com/rbx-rsml/rsml-rust.git"
readme = "README.md"
license = "MIT"

[dependencies]
phf = "0.11.3"
phf_macros = "0.11.3"
rbx_types = "1.10.0"
logos = "0.15.0"
regex = "1.11.1"
num-traits = "0.2.19"

[dependencies.proc-macro2]
version = "1.0.1"

[dependencies.quote]
version = "1.0.10"

[dependencies.syn]
version = "2.0.31"

[build-dependencies]
serde_json = "1.0.139"
phf = "0.11.3"
phf_codegen = "0.11.3"

[lib]
name = "rsml_rust"
path = "src/lib.rs"
test = true
doctest = true
bench = true
doc = true 
proc-macro = true
harness = true
edition = "2021"
crate-type = ["lib"]
required-features = ["proc-macro"]